### ISSUE TITLE
Integrate vulnerablecode 

### ISSUE THREAD

**Issue by sameer1046** [nexB/scancode.io#101]

**Comment by pombredanne** [comment]
@sameer1046 yes! @sbs2001 ping
Design-wise, what would be your idea?

**Comment by sbs2001** [comment]
Not super familiar with scancode.io, but here's a first draft : the use case here would be along the lines of "extract packages + their licenses + their vulnerabilities(if any) " 

So we have the "extract packages + their licenses"  part covered at the `scan_codebase` pipeline at https://github.com/nexB/scancode.io/blob/main/scanpipe/pipelines/scan_codebase.py and need to enrich the report with vulnerabilities. 

I can think of having a  vulnerablecode `Pipe` , which can be plugged in to the other pipelines like the `scan_codebase`. This `Pipe` will  do the following : 
(1) Take in a `CodebaseResource` (which should be scanned for packages obviously ) . 
(2) Collect all `DiscoveredPackage` related to it. Collect their purls.
(3) Make a `bulk_search` api call to vulnerablecode server with purls obtained in (2) . More or less https://github.com/nexB/vulnerablecode/pull/303#issuecomment-761801639 
(4) Iterate on the response given, for each requested `DiscoveredPackage` enrich it with vulnerablecode data. To do this we need to do some changes in models.

Model Changes:-

The vulnerability data should be on  a package level. So changes must be done at `DiscoveredPackage` . I can think of having a many2many relation of a `DiscoveredPackage` with a new model  `Vulnerability`. Essentially mirroring  the whole https://github.com/nexB/vulnerablecode/blob/137d88a1a4eb319259330fdfe4c47dbc95808850/vulnerabilities/models.py#L84 . with minor changes. This is because we not only want to know whether a package is vulnerable, but also the severity of each. 

@sschuberth ping, you guys are doing the same thing right, we can borrow some ideas here :)

**Comment by sschuberth** [comment]
> @sschuberth ping, you guys are doing the same thing at ort right ? we can borrow some ideas here :)

Sure, feel free to have a look at [our VulnerableCode integration as a ORT advisor](https://github.com/oss-review-toolkit/ort/blob/master/advisor/src/main/kotlin/advisors/VulnerableCode.kt), which enriches package metadata with security vulnerability information by leveraging our [generic Kotlin / Java client for the VulnerableCode service](https://github.com/oss-review-toolkit/ort/blob/master/clients/vulnerable-code/src/main/kotlin/VulnerableCodeService.kt).

**Comment by pombredanne** [comment]
> Sure, feel free to have a look at [our VulnerableCode integration as a ORT advisor](https://github.com/oss-review-toolkit/ort/blob/master/advisor/src/main/kotlin/advisors/VulnerableCode.kt), which enriches package metadata with security vulnerability information by leveraging our [generic Kotlin / Java client for the VulnerableCode service](https://github.com/oss-review-toolkit/ort/blob/master/clients/vulnerable-code/src/main/kotlin/VulnerableCodeService.kt).

@sschuberth that's awesome! Do you think this could be pushed as a separate reusable maven package of sorts for other could benefit from this?

**Comment by sschuberth** [comment]
> Do you think this could be pushed as a separate reusable maven package of sorts for other could benefit from this?

Definitely. That has been the plan for all our libraries in the [clients](https://github.com/oss-review-toolkit/ort/tree/master/clients) directory, and should be done as part of https://github.com/oss-review-toolkit/ort/issues/2906. Someone just needs to get it done 🙄

**Comment by tdruez** [comment]
@sbs2001 is there a VulnerableCode instance available to start making "bulk_search api call"?

**Comment by sbs2001** [comment]
@tdruez  atm no. But you can spin up one quickly using docker-compose and running some small importer

**Comment by tdruez** [comment]
@sbs2001 Any plan to deploy a VulnerableCode instance in the near future?

**Comment by sbs2001** [comment]
@tdruez  that's on @pombredanne  TODO list

**Comment by tdruez** [comment]
Completed in https://github.com/nexB/scancode.io/pull/551
