### ISSUE TITLE
Use only a single line between package copyrights in the packages list

### ISSUE THREAD

**Issue by pombredanne** [nexB/scancode.io#1010]
When I see the list of packages, it would be better to use a single line between copyrights and not two lines that take too much screen space.
```
Copyright 1997-2007 Sun Microsystems, Inc.

Copyright 2000-2007 Sun Microsystems, Inc.

Copyright 2003-2009 Sun Microsystems, Inc.

Copyright 2003-20… 
```

**Comment by MUCCHU** [comment]
Hey, I would like to take up this issue, if no one is already working on it.

**Comment by MiirzaBaig** [comment]
hey folks, I would like to upon this issue

**Comment by jayanthmahadesh** [comment]
Hello
can i get some image
not able to see what is wrong in the packages list

**Comment by Divyansh044** [comment]
Hey Everyone, I would like to work on this issue please assign this to me. I am new to open source but I will fix this issue.

**Comment by pombredanne** [comment]
@Divyansh044 we do not "assign" issues... Your statement here is enough of a signal to others that you are working on it. Please go ahead and submit a PR early.

**Comment by pombredanne** [comment]
The issues only shows up when we go through this code https://github.com/nexB/scancode.io/blob/4e274f09996a21c427a42fedc7e99920a76d9ce9/scanpipe/pipes/d2d.py#L1208 in the deploy_to_develop pipeline ... just here https://github.com/nexB/scancode.io/blob/4e274f09996a21c427a42fedc7e99920a76d9ce9/scanpipe/pipes/d2d.py#L1236 where we use "\n\n" instead of "\n"

**Comment by Divyansh044** [comment]
![image](https://github.com/nexB/scancode.io/assets/107177871/31faaae7-9606-462c-9051-98cd39ddc522)

@pombredanne  Sir can you help me in resolving this issue during the PR check

**Comment by AyanSinhaMahapatra** [comment]
@Divyansh044 you have to update the test expectations here.

Also refer to the docs: https://scancodeio.readthedocs.io/en/latest/contributing.html always before you start contributing.

As you see in the screenshot here, we have a test failure, on a test which was testing the behaviour of the package copyrights in the packages list.
Now that you've modified that behaviour, you now also have to update the expected behavior, i.e. the test expectations.

Now consider the test failure from CI (you should have also run make test on your local setup and checked for tests so this was detected earlier):

```
  File "/home/runner/work/[scancode.io/scancode.io/scanpipe/tests/pipes/test_d2d.py](http://scancode.io/scancode.io/scanpipe/tests/pipes/test_d2d.py)", line 1009, in test_scanpipe_pipes_d2d_create_local_files_packages
self.assertEqual("Copyright 2023\n\nCopyright 1984", package.copyright)
AssertionError: 'Copyright 2023\n\nCopyright 1984' != 'Copyright 2023\nCopyright 1984'
```

Here you see that `package.copyright` on the right has one less `\n` than the test expectation on the left. 
So you go to the test file where the test failure has occurred and update that.
If the test expectation was a whole file, then assert functions have a `regen` attribute which you can set to
True and run the test to regen test expectations. And then verify that the updated changes on the test expectation file
makes sense, and is in line with the change you made in code.

**Comment by Divyansh044** [comment]
@AyanSinhaMahapatra Thank you so much, Ayan. I have successfully opened a PR now without any errors.

**Comment by tdruez** [comment]
Fixed in https://github.com/nexB/scancode.io/pull/1054

@Divyansh044 Thanks for your contribution 👍
