### ISSUE TITLE
RFC: Design improved relationships for Package, Dependencies, Embeds and Requirements 

### ISSUE THREAD

**Issue by pombredanne** [nexB/scancode.io#1066]
We need to design improved models for Package, Dependencies, Embeds and Requirements. 

Some background:

- What we routinely calls "dependencies" are not really dependencies: more often these are requirements that are "resolved" to actual concrete dependencies.  To really "depend" on a software package, you need to know the exact resolved version. On the other hand, a requirement expresses the need for some range of versions (even if it's a range of a single version).

- We should distinguish a "require" relationship between packages vs. an actual "resolved" dependency to a concrete version, and track if the resolved dependency is present in the codebase or not.
 
- Dependencies (or requirements) may be only documented in a package manifest (like pom.xml) or a lockfile (like package-lock.json), or also be present in the codebase.

- We need to track also when a package contains another package (or for that matter when an app contains or embeds packages). 

Therefore we may have three levels of tree-like data we need to track for packages:
- "potential" requirements (we call these dependencies today). This is a logically a flat list of PURLs with VERS attached to a package instance. 
- "resolved" dependencies (we call these dependencies today too, but sometimes also packages). This is logically a tree (or graph) of PURLs with a resolved version. Each such dependency is derived and satisfies one or more "requirement".   
- "embeds" are packages embedded in other packages, e.g., they are physically copied, vendor and or built into a product codebase. These could have been the results of provisioning/fetching resolved dependencies, or could be a straight copy. These are not much tracked as such today.

We have agreed on some key model updates, based on discussions here and in our weekly calls:
- [x] Enhance ScanCode.io models to support relating dependencies to packages
- [x] Enhance ScanCode Toolkit models to support relating dependencies to packages
- [ ] nexB/dejacode#138
- [ ] nexB/purldb#485
-  ~~Enhance python-inspector models to support relating dependencies to packages using the new models~~
- ~~Enhance nuget-inspector models to support relating dependencies to packages using the new models~~
- ~~Create dependency-inspector to relate dependencies to packages using the new models~~

The https://github.com/nexB/dependency-inspector tickets to create lockfiles are:
- [x] https://github.com/nexB/dependency-inspector/issues/3
- [x] https://github.com/nexB/dependency-inspector/issues/5
- [x] https://github.com/nexB/dependency-inspector/issues/4
- [x] https://github.com/nexB/dependency-inspector/issues/12
- [x] https://github.com/nexB/dependency-inspector/issues/10
- [x] https://github.com/nexB/dependency-inspector/issues/8
- [x] https://github.com/nexB/dependency-inspector/issues/11

Then for the effective resolution of dependencies as a tree from manifests and lockfiles:
- [x] npm: https://github.com/nexB/scancode.io/issues/1201 and https://github.com/nexB/scancode.io/issues/1237
- [x] pypi: https://github.com/nexB/scancode.io/issues/1262
- [x] nuget: https://github.com/nexB/scancode.io/issues/1263
- [x] cocoapods: https://github.com/nexB/scancode.io/issues/1279
- [x] swift: https://github.com/nexB/scancode.io/issues/1278

And beyond:
- https://github.com/nexB/dependency-inspector/issues/13

Here are also some related issues, but not directly need to complete this feature: 
- Support packages embedded in other packages
  - https://github.com/nexB/scancode-toolkit/issues/2418
  - https://github.com/nexB/purldb/issues/177
  - https://github.com/nexB/purldb/issues/163  
- Improve the definition of a package and dependency
  - https://github.com/nexB/scancode.io/issues/885
  - https://github.com/nexB/scancode.io/issues/888
- Introduce successor packages https://github.com/nexB/purldb/issues/175
- and also https://github.com/nexB/python-inspector, https://github.com/nexB/nuget-inspector and other inspectors.

**Comment by pombredanne** [comment]
Note that this is as much for ScanCode.io than it is for ScanCode Toolkit, DejaCode and PurlDB

**Comment by AyanSinhaMahapatra** [comment]
Summarizing the discussion we had on the community call on this issue:

We need to have dependencies also as packages, and not
as a seperate model (with the skinny purl only package data and optionally
resolved packages nested inside) we have today. And dependencies here
would be preserved as relationships between these packages, and the actual
primary package -> secondary packages (either dependencies/embedded packages)
would also be preserved by creating relationships between them.

Here we have some types of packages:

1. Primary package instances
2. Resolved package dependency with package data/files
3. Resolved package dependency without package data/files (just PURL)
4. Secondary/Embedded package (files embedded in primary package files)
5. Package requirements (package + version range)

This approach has some benefits:

- We don't have to change massively our package models, just some attributes addition/deletion
  as we are only changing how we report the data within those models, and the output format
  remains the same essentially.
- Resolved packages won't be nested, eveything would be there as package instances.
- This is straightforward, as dependency is really a relationship and not a seperate model.
- Similar to what users expect/other tools provide, and essentially what we will have if
  we scan a package with pre-resolved dependencies present in the code tree, there too
  since we have the packages detected as instances, we have them as packages.

For example, in SCIO we could have filters for primary packages, secondary/embedded packages,
so that these are differentiated and looked at seperately as required, and the dependency tab
could have the relations between them.

Two possible implementations in this:

a) We have everything (packages, resolved/embedded dependencies, dependency purls and even requirements)
   returned as Packages.
   - Would be less confusing and straightforward, having everything stored similarly.
   - We can do a resolve requierments to the oldest version available within
     the required versions, or something similar, to have a proper package instance.

b) We have everything else  but requirements (packages, resolved/embedded dependencies, dependency purls)
   as packages. Requirements (does not have exact version, therefore does not point to a package)
   - Requirements do not have a version, so these aren't really package instances as
     they are not concrete packages which can be identified in a unique way. So these
     should not be confused with packages.
   - Even for dependency purls we can get package metadata/download the packages and scan them, but we
     cannot to the same for dependency requirements, as they are not package instances.
   - If we try to resolve these dependency requirements incorrectly (to the oldest version available within
     the required versions) this would be incorrect and misleading for any compliance. As package licenses
     could change between versions and without correct versions we cannot check vulneribilities. So these
     are essentially false positives.

cc @pombredanne @tdruez

**Comment by pombredanne** [comment]
The latest design is to go in this direction:

- We are transforming the DiscoveredDependency model to add a foreign key to the corresponding resolved DiscoveredPackage something like a "resolved_to" relationship
- We will have a dependency resolution process in a pipeline where we look at the dependencies and resolve them to actual found packages or can also use a resolver, even if very crude.
- We may also track if a package is physically found on disk in a codebase
- This can stay optional
- We will need to ensure that we are doing the right thing too on the scancode toolkit side
- The same solution will be then propagated to PurlDB and possibly to DejaCode


See also attached:

![deps-resolution-in-scancode-1](https://github.com/nexB/scancode.io/assets/675997/412a3e6b-acd7-41b1-9b2f-bb09c4aa6d4b)
![deps-resolution-in-scancode-2](https://github.com/nexB/scancode.io/assets/675997/3f9a958c-0daa-4f0d-99ca-414f4829b413)

**Comment by pombredanne** [comment]
@AyanSinhaMahapatra I had some other notes too... did you capture some?

**Comment by pombredanne** [comment]
We have a mostly working PR with https://github.com/nexB/scancode.io/pull/896 by @Hritik14

**Comment by tdruez** [comment]
I would recommend an implementation in multiple stages:
1. https://github.com/nexB/scancode.io/pull/1240
2. Add the resolution processing to create packages and feed the new `resolved_to` field. That's also at that time we can add the new DiscoveredPackage fields that will help to qualify the package "level" regarding the dependency tree.
3. Add the methods to collect and use the dependency tree within a project and include the tree in the outputs such as CycloneDX.

**Comment by tdruez** [comment]
@AyanSinhaMahapatra The new `resolved_to` field is now merged.

Could you start a PR on the resolution part? https://github.com/nexB/scancode.io/issues/1066#issuecomment-2117703563
As a side note we want to keep the resolution tree, meaning a package defined as `resolved_to` can also be defined as a `for_package`. The model should support this approach fine.

**Comment by pombredanne** [comment]
Here are some notes as how I understand this model will work:

We are updating these existing relationships (and their reverses): 
- DiscoveredDependency  > for_package > DiscoveredPackage
- DiscoveredPackage  > declared_dependencies > DiscoveredDependency


We are creating these new relationships (and their reverses): 
- DiscoveredDependency  > resolved_to > DiscoveredPackage
- DiscoveredPackage  > resolved_dependencies > DiscoveredDependency

A resolution would start with this:

1. Starting "universe":

```
foo@1.2
 - direct deps: bar > 2.0
 
bar@3.0
 - direct deps: baz >= 1.0

baz@1.0
 - direct deps: None
```

2. If we resolve for foo@1.2 then the Tree is:
```
foo@1.2
 - direct deps: bar > 2.0
   - resolved_to: bar@3.0
     - direct deps: baz >= 1.0
       - resolved_to: baz@1.0

```

**Comment by Hritik14** [comment]
As per above and #896, now `ResolvedDependency` instead of being a concrete model of its own will act as an associative table that connects any two `DiscoveredPackage` in a many-to-many fashion.
This looks like the following:

![scio-transitive-1 drawio](https://github.com/nexB/scancode.io/assets/7457065/e2a2f5f1-72cc-423b-b22f-34a3446087f3)


Now, adding the above suggestion of `direct deps` or `requirement` might look something like:

![scio-transitive-2 drawio](https://github.com/nexB/scancode.io/assets/7457065/1f7cda22-adf9-4dad-83f3-b88975049524)


A package has requirements, a requirement resolves to a dependency and a dependency maps to a package. Packages retain their many to many relationship via the dependency associative but every dependency also has a one to one relationship with a requirement.

@tdruez 
#1240 looks good to me, although should we call `resolved_dependencies` as `resolved_parents` or just `parents` ? Having `declared_dependencies` and `resolved_dependencies` both on `DiscoveredPackage` does not make sense.

**Comment by pombredanne** [comment]
@Hritik14 If I expand on the topic of https://github.com/nexB/scancode.io/issues/1066#issuecomment-2120835558 then we have these records and relationships (I have added 

### Before resolution:
- DiscoveredPackage  > declared_dependencies > DiscoveredDependency
>       foo@1.2                 >             bar > 2.0
>       foo@1.2                 >             biz > 3.0
>       bar@3.0                 >             baz >= 1.0
>       biz@4.0                 >             baz >= 0.1
>       baz@1.0

- DiscoveredDependency  > for_package > DiscoveredPackage
>       bar > 2.0               >             foo@1.2
>       biz > 3.0               >             foo@1.2
>       baz >= 1.0              >             bar@3.0
>       baz >= 0.1              >             biz@4.0

### After resolution:

- DiscoveredPackage  > resolved_dependencies > DiscoveredDependency
>       bar@3.0                 >             bar > 2.0
>       baz@1.0                 >             baz >= 1.0
>       baz@1.0                 >             baz >= 0.1
>       biz@4.0                 >             biz > 3.0


- DiscoveredDependency  > resolved_to > DiscoveredPackage
>       bar > 2.0               >             bar@3.0
>       baz >= 1.0              >             baz@1.0
>       baz >= 0.1              >             baz@1.0
>       biz > 3.0               >             biz@4.0




What does having an intermediate DiscoveredRequirement brings that we cannot do with the newly updated model? (The idea here is to avoid changing fundamentally the model structure)


With that said `resolved_dependencies`

**Comment by AyanSinhaMahapatra** [comment]
> Could you start a PR on the resolution part? https://github.com/nexB/scancode.io/issues/1066#issuecomment-2117703563
As a side note we want to keep the resolution tree, meaning a package defined as resolved_to can also be defined as a for_package. The model should support this approach fine.

@tdruez @pombredanne I've added an initial implementation for the resolution process, this is now:
* populating the newly added `resolved_to` attribute in the dependency relationships
* creating new resolved packages from the `resolved_package` attribute we have already in SCTK output. This is stored in dependencies for PackageData objects, for the corresponding lockfile resource.
* Added this as optional groups in both `resolve_dependencies` and `inspect_packages` pipeline, uses the same function for this. (need feedback on the UI/pipelines flow and group name, is this okay? Or should we do an addon pipeline instead) 

Things remaining [WIP]: 
* Add also resolved_packages for dependencies in other manifests with `is_resolved` as True (but these might not have the fully resolved tree, just some pinned dependencies) 
* Do some sort of merging of dependency relations (same dependency/requirements present in multiple manifests)
* On the SCTK side improving the dependencies parsing in npm, yarn and pnpm with https://github.com/nexB/scancode-toolkit/tree/improve-npm-support to fully address https://github.com/nexB/scancode.io/issues/1237

Questions:
I'm not sure on the attribute names for the following:
> add the new DiscoveredPackage fields that will help to qualify the package "level" regarding the dependency tree.

Can we implement the above with https://github.com/nexB/scancode.io/issues/880
where we can have some indication of a Package being created from static resolver?

**Comment by AyanSinhaMahapatra** [comment]
This is now there with https://github.com/nexB/scancode.io/commit/08c54b158950c8ec0c8e86b1e9d69233f9310297 and support has been added for pypi, poetry, swift, nuget, cocoapods, npm, yarn also with additional help from deplock at https://github.com/nexB/dependency-inspector to generate lockfiles if they are not present, and then parse, store and resolve dependencies to form a graph. 
Follow up issues are there on scancode-toolkit, dejacode, purldb.
Closing!
