### ISSUE TITLE
Codebase file navigator display could be delayed to after the scan is complete?

### ISSUE THREAD

**Issue by pombredanne** [nexB/scancode.io#1169]
The small "Codebase" file navigator in project gets confused with a 404 if a file is a link
See for instance
http://deb.debian.org/debian/pool/main/o/openssh/openssh_9.2p1.orig.tar.gz
With a scan single package ... the LICENCE file leads to a 404

**Comment by tdruez** [comment]
@pombredanne the LICENCE file is not a link, it's a proper file. Also clicking on the LICENCE entry from the "Codebase" panel does properly return the Resource details view.

I'm guessing that you were trying to use the links from the Codebase panel before the CodebaseResources were created in the DB, ie before the end of the pipeline execution.

If that is the case, maybe we should not display that panel until the first pipeline is completed, or if the CodebaseResource count is 0, since those are required to display any information about the resources.

**Comment by pombredanne** [comment]
@tdruez good catch! .... let me rename the issue.

**Comment by pombredanne** [comment]
On the other hand I like it as it is, so let's not change anything.
