### ISSUE TITLE
Questionable accuracy of results for base debian slim image

### ISSUE THREAD

**Issue by cco3** [nexB/scancode.io#128]
I have concerns about some of these results on just the base debian-slim image.

For example, results for `libstdc++6`
```
 "license_expression": "agpl-3.0 AND amd-historical AND artistic-1.0 AND artistic-2.0 AND bsd-new AND bsd-no-disclaimer AND bsd-no-disclaimer-unmodified AND bsd-original AND bsd-original-uc AND bsd-original-uc-1986 AND bsd-simplified AND bsla AND d-zlib AND delorie-historical AND flex-2.5 AND gcc-exception-3.1 AND gfdl-1.2 AND gfdl-1.3-plus AND gpl-1.0-plus AND gpl-2.0 AND gpl-2.0 WITH gcc-linking-exception-2.0 AND gpl-2.0-plus AND gpl-3.0 AND gpl-3.0-plus AND gpl-3.0-plus WITH gcc-exception-3.1 AND hs-regexp AND intel-osl-1989 AND intel-osl-1993 AND lgpl-2.0 AND lgpl-2.0-plus AND lgpl-2.1 AND lgpl-2.1-plus AND lgpl-3.0-plus WITH cygwin-exception-lgpl-3.0-plus AND newlib-historical AND nilsson-historical AND osf-1990 AND other-copyleft AND other-permissive AND proprietary-license AND public-domain AND sunpro AND tex-exception AND unicode AND unknown AND unknown-license-reference AND uoi-ncsa AND viewflow-agpl-3.0-exception AND warranty-disclaimer AND wide-license AND x11 AND x11-hanson AND x11-lucent AND zlib AND zlib-acknowledgement"
```

(It's a txt file because I can't upload .json apparently)
[Debian Slim.txt](https://github.com/nexB/scancode.io/files/6260166/Debian.Slim.txt)

**Comment by pombredanne** [comment]
@cco3 thanks! Would this image be close enough ? https://hub.docker.com/layers/debian/library/debian/stable-slim/images/sha256-dfdeee682f344162123662fd0fb8665d7b2d7bf3607ce4c6a91e542047e5bc6f?context=explore

**Comment by pombredanne** [comment]
Actually I have the image id in the scan !

**Comment by pombredanne** [comment]
`$ docker pull debian@sha256:a7d45592371e040910bac139129b3222d7bee5155434776828da25cb4623daf0` is the image

**Comment by pombredanne** [comment]
For reference we are tracking all these related issues in #103 "meta issue: Improve Debian package reported license"
Also the detection with the latest scancode.io has changed:

1. we have a new bug where we do not detect at all anymore the copyright for libstdc++6 ... this is because this copyright file is a link to the `gcc-10-base` copyright and that we stopped extracting links which was a problem BUt is creating this new problem
2. the license detection has evolved and been improved in ScanCode toolkit and therefore the set of detected license is better

For instance, we had these licenses detected for the `gcc-10-base` copyright file in your scan:

> agpl-3.0 AND amd-historical AND artistic-1.0 AND artistic-2.0 AND bsd-new AND bsd-no-disclaimer AND bsd-no-disclaimer-unmodified AND bsd-original AND bsd-original-uc AND bsd-original-uc-1986 AND bsd-simplified AND bsla AND d-zlib AND delorie-historical AND flex-2.5 AND gcc-exception-3.1 AND gfdl-1.2 AND gfdl-1.3-plus AND gpl-1.0-plus AND gpl-2.0 AND gpl-2.0 WITH gcc-linking-exception-2.0 AND gpl-2.0-plus AND gpl-3.0 AND gpl-3.0-plus AND gpl-3.0-plus WITH gcc-exception-3.1 AND hs-regexp AND intel-osl-1989 AND intel-osl-1993 AND lgpl-2.0 AND lgpl-2.0-plus AND lgpl-2.1 AND lgpl-2.1-plus AND lgpl-3.0-plus WITH cygwin-exception-lgpl-3.0-plus AND newlib-historical AND nilsson-historical AND osf-1990 AND other-copyleft AND other-permissive AND proprietary-license AND public-domain AND sunpro AND tex-exception AND unicode AND unknown AND unknown-license-reference AND uoi-ncsa AND viewflow-agpl-3.0-exception AND warranty-disclaimer AND wide-license AND x11 AND x11-hanson AND x11-lucent AND zlib AND zlib-acknowledgement


In the latest version we now have something like this:

> artistic-1.0 AND bsd-new AND bsd-original-uc AND bsla AND flex-2.5 AND gcc-exception-3.1 AND
  gfdl-1.2 AND gfdl-1.3-plus AND gpl-1.0-plus AND gpl-2.0 AND gpl-2.0-plus AND gpl-3.0 AND gpl-3.0-plus
  AND lgpl-2.0-plus AND lgpl-2.1 AND lgpl-2.1-plus AND lgpl-3.0-plus WITH cygwin-exception-lgpl-3.0-plus
  AND newlib-historical AND osf-1990 AND other-copyleft AND other-permissive AND public-domain
  AND sunpro AND unicode AND unknown AND unknown-license-reference AND warranty-disclaimer


This is still incorrect, but improved.

**Comment by cco3** [comment]
Feel free to close this if it's not adding anything to #103

**Comment by tdruez** [comment]
Closing in favor of #103
