### ISSUE TITLE
Add a UI tutorial

### ISSUE THREAD

**Issue by hyounes4560** [nexB/scancode.io#241]
Create a UI tutorial that follows the same style and layout as other CL tutorials.

**Comment by tdruez** [comment]
@hyounes4560 we want to split the new UI tutorial in 2 chapters:

- `tutorial-3.rst`: **Analyze Docker Image (Web UI)**

Similar to the command line tutorial (with a different input) and uses the Web UI. Using `docker://alpine/httpie` as input in the "Download URL" field to expose the image fetching feature.
The goal here is to create and launch a pipeline and to provide a walk through of the various UI features only as related to a pipeline creation, launch, its runtime, log and completion as well as its possible runtime errors.

- `tutorial-4.rst`: **Review Scan Results (Web UI)**

The "Review Scan Results" chapter is the direct continuation of "Analyze Docker Image", where the presented results are related to the previous pipeline run.
The goal here is to show how the web UI is used to review scan results, to focus on the UI features to navigate the summary and graps, browse package and resources details and hyperlinking between these different areas in order to guide on how scan results can be review.
