### ISSUE TITLE
Connection kept alive when creating a new project until pipeline is finished when execute_now is true

### ISSUE THREAD

**Issue by aalexanderr** [nexB/scancode.io#321]
Issue:
I noticed this when I scanned all ONAP dockers that after POST to /api/projects/ with execute_now:true- connection is kept alive during execution of given pipeline.

How I noticed it - made a simple script to scan all images we have in ONAP:
```bash
#!/bin/bash

declare -a images=("nexus3.onap.org:10001/onap/vid:8.0.2"
"nexus3.onap.org:10001/onap/vnfsdk/refrepo:1.6.3"
"nexus3.onap.org:10001/rabbitmq:alpine")

JSON_FMT='{"name":"%s","input_urls":"docker://%s","pipeline":"docker","execute_now":"true","extra_data":{"onap-daily":"05-09-2021"}}\r'
AUTH_FMT='Authorization: %s\r'

for img in "${images[@]}"
do
        curl -v -X POST \
                -H "Accept: application/json" \
                -H "Content-Type: application/json" \
                -H $(printf "$AUTH_FMT" $SECRET_KEY) \
                -d $(printf "$JSON_FMT" $img $img) \
                'http://127.0.0.1:8001/api/projects/'
done
```
And was surprised to see that each POST was being kept alive until server returned info after scanning the project. I have limited experience with webdev but from what I've gathered the same happens in web view.

Expected behavior:
Server responds directly after creation of project with uuid of project & run uuid so user can manage the project (like add additional pipelines to run) & check given run status. 

This would allow querying server while pipeline is running using  `/api/runs/{uuid}` or new endpoint `/api/runs/{uuid}/status` that would just return info about given run status to make it short and sweet for polling.

**Comment by tdruez** [comment]
@aalexanderr How are you running the application? Docker or single threaded development mode with `make run`?

**Comment by aalexanderr** [comment]
i'm using `make run` on dev setup (`make dev`) but with `SCANCODEIO_PROCESSES="6"` Is this related to only one celery worker in dev setup?
checked both with 21.8 version & with current tip.

**Comment by tdruez** [comment]
`make run` is running the Django `runserver` command with this setup the tasks are directly consumed by the `runserver` process within the HTTP request since no workers are running on the side.

If you want a proper setup with workers that will run the Pipeline task asynchronously, you may want to run with Docker.
Alternatively, you can set `CELERY_TASK_ALWAYS_EAGER=False` in your .env file, start a redis server, and run `make worker` in another terminal tab.
With both of those approaches, your HTTP requests will close directly and the Pipelines will be handle by the workers.

I'm adding clarification in the documentation about this, see https://github.com/nexB/scancode.io/pull/322/files#diff-d9b149498982c0663c3b7170398773361ed5678f1a627e9c2fd8d2c955c563dbR202-R213

**Comment by aalexanderr** [comment]
Thanks a lot for explanation, and doc change, I'm closing this issue as #322 clarifies it in docs
