### ISSUE TITLE
getting error while docker-compose up

### ISSUE THREAD

**Issue by sameer1046** [nexB/scancode.io#327]
ModuleNotFoundError: No module named 'scancodeio.settings.base'; 'scancodeio.settings' is not a package

i have created the secret key in .env file.

**Comment by tdruez** [comment]
Hi @sameer1046 thanks for reporting this.
The settings system was simplified recently and one reference to the old setting file was not removed.

The problem should now be fixed with https://github.com/nexB/scancode.io/commit/fa0a054bc3291e89facbb9ea5c1f64f47793ed10

Could you checkout the latest main branch and try again?

**Comment by tdruez** [comment]
@sameer1046 Closing this one. Feel free to re-open if you still encounter the issue.
