### ISSUE TITLE
Codebase resource "Name" is not the filename 

### ISSUE THREAD

**Issue by pombredanne** [nexB/scancode.io#467]
I found highly surprising that the name field of the CodebaseResource model (and therefore also in the UI) is NOT the actual file name or directory name, but rather has been stripped from it's extension, which is stored in a separate field. What's the rationale for this?

**Comment by JonoYang** [comment]
This inconsistency is causing problems when updating the application package scanning step with the new Package assembly methods from packagedcode. The assembly methods on different Package handlers look for particular Package manifest files by their filename with extension (e.g. https://github.com/nexB/scancode-toolkit/blob/develop/src/packagedcode/npm.py#L72). Because scancode.io stores the filename without the extension in the `name` field of `CodebaseResource`, these manifest files are never found and the detected Package data cannot be processed properly.

**Comment by tdruez** [comment]
@JonoYang is https://github.com/nexB/scancode.io/compare/package-scanning-update ready for review?
I don't see any PR yet ;)
