### ISSUE TITLE
Support newer versions of python

### ISSUE THREAD

**Issue by cco3** [nexB/scancode.io#54]
Is there a reason python3.6 is specifically required?  On some Debian environments, it is impossible to use `-m venv` without the newest version of python.

**Comment by pombredanne** [comment]
@cco3 3.6 is the base version were we test and that we support for now here and in all dependent libs... there is no hard requirement on it though, and we should enable CI and test runs on all version from 3.6 to 3.9 alright (and also first on all supporting libraries too)

**Comment by tdruez** [comment]
The main reason for 3.6 is the dependency on ScanCode-toolkit https://scancode-toolkit.readthedocs.io/en/latest/getting-started/install.html#prerequisites
If the toolkit supports Python up to 3.9, this should be easy to enable 3.6 to 3.9 support in ScanCode.io
I'll start a branch to run the tests on 3.6+ versions.

**Comment by tdruez** [comment]
Support for 3.6 to 3.9 is going fairly well. 

There's only 1 blocker: the `scancode-toolkit` dependency on `typing` as `typing` is now part of the standard library since Python 3.5 and installing the backport is a source of issues on Python3.7+

See https://github.com/python/typing/issues/573 and https://github.com/python/typing/issues/573#issuecomment-405986724 for the solution.

The local workaround is to uninstall `typing` right after installing the `scancode-toolkit`.
@pombredanne Could we implement a proper fix on the toolkit side?

**Comment by tdruez** [comment]
Support for Python 3.6 to 3.9 merged in `main` branch.
Keeping the ticket open to remove the workaround at https://github.com/nexB/scancode.io/blob/main/Makefile#L52 once the new version of the toolkit and commoncode are available.

**Comment by tdruez** [comment]
Support for Python 3.6 to 3.9 now officially supported with the new ScanCode-toolkit 21.2.9 version.
