### ISSUE TITLE
ScanCode.io failure on systemd-252.tar.gz

### ISSUE THREAD

**Issue by DennisClark** [nexB/scancode.io#556]
I created a new project called systemdv252 to scan systemd-252.tar.gz which is available from 
https://github.com/systemd/systemd/archive/refs/tags/v252.tar.gz

The ScanCode.io screen simply shows a red "Failure" indicator and I do not see any additional information.

**Comment by tdruez** [comment]
After investigation ScanCode-toolkit is failing (timeout) on this file `systemd-252/test/fuzz/fuzz-unit-file/oss-fuzz-8827`
[oss-fuzz-8827.zip](https://github.com/nexB/scancode.io/files/9954307/oss-fuzz-8827.zip)

On the ScanCode.io, we should improve the reporting on those type of failure (hard to catch as long as we use subprocess in the `scan_package` pipeline)

A proper fix is also required on the toolkit side, it's a made up fuzz text for testing and it's rather small, it should not reach the 1h timeout during scanning.

**Comment by tdruez** [comment]
The underlying issue is that the ScanPackage pipeline depends on a subprocess call to the `scancode` command.
If `scancode` fails, there's no easy way to save this as a ProjectError and continue the pipeline run.

A better approach would be to replace this approach by proper api calls, as we did for the Scanners in the ScanCodebase pipeline (For example: `get_copyrights`, `get_licenses`, `get_package_data`)

The 3 missing pieces as callable API for the ScanPackage pipeline are:
- `--classify`: FileClassifier(PreScanPlugin)
- `--is-license-text`: IsLicenseText(PostScanPlugin)
- `--summary`: ScanSummary(PostScanPlugin)

**Comment by tdruez** [comment]
With the changes from https://github.com/nexB/scancode.io/issues/798 , the `scan_package` pipeline on https://github.com/systemd/systemd/archive/refs/tags/v252.tar.gz now completes successfully and reports the file timeout as a Project message:
![Screenshot 2024-01-08 at 11 05 26](https://github.com/nexB/scancode.io/assets/489057/bccb8650-72c2-44c6-91cb-ad46a40f76fc)
