### ISSUE TITLE
Textbox dimensions not constrained by min/max height and width

### ISSUE THREAD

**Issue by OctoPie23** [nexB/scancode.io#606]
The textbox design requires some layout adjustments.
When stretching the textbox with respect to the parent class, there should be a `max-height` and `max-width `as well as a `min-height` and `min-width`. 

[Screencast from 14-2-23 07:23:26 अपराह्न +0545.webm](https://user-images.githubusercontent.com/76906722/218756695-0a0342c3-0c62-4e8d-92b7-c26efd2bc2c4.webm)

**Comment by OctoPie23** [comment]
`/label enhancement`

**Comment by OctoPie23** [comment]
@AyanSinhaMahapatra @pombredanne Take a quick look at it.

**Comment by tdruez** [comment]
@OctoPie23 This UI is inherited from the [Django REST framework](https://www.django-rest-framework.org/) library and its underlying CSS libraries.
You may want to suggest a fix over there but this is not really an issue that worth spending time on as it's likely fixed in recent versions of bootstrap.
Also this part of the UI is available as a convenient way to test the API but not a realistic way to interact with it.
