### ISSUE TITLE
ABOUT files should be mapped when their documented resource is mapped

### ISSUE THREAD

**Issue by pombredanne** [nexB/scancode.io#825]
ABOUT files should be mapped when their documented resource is mapped. They should be mapped to the same origin and license (e.g., the package documented in the ABOUT file) AND the .LICENSE and .NOTICE if any should also be mapped. All these assigned a status and should not be part of further scans

**Comment by AyanSinhaMahapatra** [comment]
@pombredanne  I've implemented this in the commit above, but just to confirm:
> All these assigned a status and should be part of further scans
Did you mean to say they should not be scanned further?

**Comment by pombredanne** [comment]
> Did you mean to say they should not be scanned further?

Yes... I fat fingered it!

> Also just detailing the changes to confirm this is what we want:
> 
>  - Files mapped by ABOUT file are now tagged with status: about-mapped
>  - Companion files for the ABOUT files (License/Notice etc) and the ABOUT file itself are also tagged with status: about-mapped
>  - Files with status about-mapped are skipped from the file scanning step at last

Actually all files mapped through an ABOUT file should be mapped super early in the pipeline and tagged such that there is NOT ANY other step that processes them further be it for mapping, matching, scanning or anything else. Their analysis is essentially "done".

**Comment by tdruez** [comment]
@AyanSinhaMahapatra ready to be closed?

**Comment by AyanSinhaMahapatra** [comment]
> is NOT ANY other step that processes them further be it for mapping, matching, scanning or anything else.

@pombredanne 
Most other pipes in the d2d pipeline already was doing this using `.no_status()`. For now only `map_jar_to_source` and `map_javascript` does not have filters by status, but they have filters by extension which selects files.

I've only modified the `scan_mapped_from_for_files` pipe to ignore only the files which are summarized by the ABOUT files, since that was the main issue. 

@tdruez everything mentioned in https://github.com/nexB/scancode.io/issues/825#issue-1824598825 is implemented, but should we do more based on the above comments? ^

**Comment by pombredanne** [comment]
@AyanSinhaMahapatra I am letting find the best solution with @keshav-space and @tdruez if need be :)
And my point stands: things mapped with an ABOUT file **SHOULD NOT** be further analyzed... if this means changing other steps, then so be it.

**Comment by keshav-space** [comment]
Ack @pombredanne , will update the `map_javascript` to ignore the files with `about file` status.

**Comment by AyanSinhaMahapatra** [comment]
Closing this issue as this is completed.
