### ISSUE TITLE
Queries Related to SCANCODE.IO 

### ISSUE THREAD

**Issue by parvjain639** [nexB/scancode.io#832]
1.Can we Scan Particular code files with scancode.io?
2.Today, companies restrict/ban the internal use of generative AI tools like ChatGPT for fear of data/IP leaks. What guardrails/safeguards does Scancode.io use to protect from proprietary data/info leaks. What are retention policies?
3. Does Scancode.io Scan Full Dependency Tree? What is the Maximum Depth for Manifest Scanning?
4. Is there any Command to add inputs after once the Pipeline is Executed?

**Comment by tdruez** [comment]
> 1.Can we Scan Particular code files with scancode.io?

You can `exclude` file patterns using the Project settings. We do not have the option to limit the scanning to specific files only. As a workaround, make an archive of the particular file you want to scan and use this archive as your input.

> 2.Today, companies restrict/ban the internal use of generative AI tools like ChatGPT for fear of data/IP leaks. What guardrails/safeguards does Scancode.io use to protect from proprietary data/info leaks. What are retention policies?

I'm not sure how this applies to ScanCode.io. Please provide more context.

> 3. Does Scancode.io Scan Full Dependency Tree? What is the Maximum Depth for Manifest Scanning?

@pombredanne should be able to provide more details about the dependencies.

> 4. Is there any Command to add inputs after once the Pipeline is Executed?

Inputs are frozen by design once a pipeline has started on a Project. What is your use case for modifying inputs post-scan?

**Comment by pombredanne** [comment]
> 1.Can we Scan Particular code files with scancode.io?

You can also just create a project only for the file you care for as inputs 

> 2.Today, companies restrict/ban the internal use of generative AI tools like ChatGPT for fear of data/IP leaks. What guardrails/safeguards does Scancode.io use to protect from proprietary data/info leaks. What are retention policies?

Same as @tdruez ... I am not sure I get the point... can you elaborate on what your concern is wrt. code scanning? You can install everything locally in an airgapped environment 100% on premises and under your control. So if you control everything, I guess nothing can leak?

> 3. Does Scancode.io Scan Full Dependency Tree? What is the Maximum Depth for Manifest Scanning?

The scanning depth is a red herring invented by some commercial company that I will not name ;) This is BS they convey. ScanCode scans everything provided at full depth. What ScanCode does not always do (yet) is to resolve all the dependencies, as we have support for only some packages types for this for now. You should instead scan a codebase where dependencies have been resolved first. Also scanning the deployed code is always a good/better option since you will get all resolved deps there too. 

>  4. Is there any Command to add inputs after once the Pipeline is Executed?

No, it is not possible to add inputs once at least one pipeline was executed. This is a design decision we made to avoid data inconsistencies. Instead you can either:
a. Click on Settings and reset your project (this will wipe all the existing scanned data) and then re-add the pipelines you want
b. Create a new project

**Comment by parvjain639** [comment]
> You can `exclude` file patterns using the Project settings. We do not have the option to limit the scanning to specific files only. As a workaround, make an archive of the particular file you want to scan and use this archive as your input.

![Screenshot 2023-08-01 100629](https://github.com/nexB/scancode.io/assets/140686999/484cdcd7-cd71-4e2c-98c1-654ad5c259f1)

We are not getting any options as per given in documentation. So Is there any command to include those options?

> What is your use case for modifying inputs post-scan?

We want to rescan our project by a particular time spam. so is there any automated way of re-scanning projects/ Scheduling rescanning within a time spam?

> we have support for only some packages types for this for now.

Is there any list of packages which you are Including or Excluding?

**Comment by tdruez** [comment]
> We are not getting any options as per given in documentation. So Is there any command to include those options?

The "Project archive" feature is a completely unrelated feature.
Our initial suggestion is that you create an archive (zip, tar.gz, ...) of the subset of files you want to scan. This happens outside of ScanCode.io
You can then use this archive as your ScanCode.io input.

> We want to rescan our project by a particular time spam. so is there any automated way of re-scanning projects/ Scheduling rescanning within a time spam?

Assuming you meant "time span", there is no automated built-in way to trigger a scan.
But you can call the ScanCode.io CLI or REST API through simple scripts executed on your desired schedule using crontab.

I'm currently writing documentation for https://github.com/nexB/scancode.io/issues/828, you'll be able to see concrete examples there soon.

> Is there any list of packages which you are Including or Excluding?

Nothing is actively "excluded" but some package types may not be supported. You can refer to https://scancode-toolkit.readthedocs.io/en/stable/reference/available_package_parsers.html

**Comment by parvjain639** [comment]
Thank You so much for your  Quick Response. It is really helpful to us.

Earlier, We have run all the pipelines for this input file. we have got this result attached below.

![Screenshot 2023-08-01 111803](https://github.com/nexB/scancode.io/assets/140686999/1d75295b-b0ff-4362-8ad4-99ef1f01e0fd)

According to your instructions, we have run only Docker and Find_Vulnerabilities pipeline we are getting this result attached below.

![Screenshot 2023-08-01 151506](https://github.com/nexB/scancode.io/assets/140686999/a6cd697e-d066-41a9-ad51-71e86ae8f0eb)

Can you please clear our doubts why the results are not same for Vulnerabilities and errors?
Mainly we are scanning projects for Vulnerabilities, Errors and Dependency
But there is a great difference between both (PROJECT INPUTS ARE EXACTLY SAME IN BOTH THE CASES)
Earlier vulnerabilities were 6 but now only 1
Earlier errors were 10 but now 0
Earlier Dependencies were 752 but now only 89

I guess Vulnerabilities and Errors should be same in both the cases!

Also, when I am Re-running an Docker Image with Docker Pipeline after completion of this pipeline the results of Packages and dependencies are getting doubled. Can you please explain us the same why this happens?

**Comment by tdruez** [comment]
> Can you please clear our doubts why the results are not same for Vulnerabilities and errors?

As explained before, all those pipelines are not meant to be run side by side on the same project. Each pipeline has its way to create resources, packages, etc. Running all of those will create duplicated data.

Since the packages, resources, and dependencies in the first project are not the same as in the second one, you cannot expect to get the same results.

> I guess Vulnerabilities and Errors should be same in both the cases!

Different pipeline runs will result in different results. There's no reason to expect otherwise.

> Also, when I am Re-running an Docker Image with Docker Pipeline after completion of this pipeline the results of Packages and dependencies are getting doubled. Can you please explain us the same why this happens?

You do not want to "re-run" the same pipeline for a given project.
If you need to "scan" again, you create a new project. Or as @pombredanne suggested, if you do not wish to keep the data of the previous run, you can "reset" your project and restart the pipeline on a clean slate.
