### ISSUE TITLE
D2D: Add progress logging to scan_mapped_from_for_files step

### ISSUE THREAD

**Issue by pombredanne** [nexB/scancode.io#908]
It would nice to have progress logging for the "scan_mapped_from_for_files" step that can be long running on large well-mapped codebases

**Comment by pombredanne** [comment]
Same for flag_mapped_resources_archives_and_ignored_directories

**Comment by tdruez** [comment]
> It would nice to have progress logging for the "scan_mapped_from_for_files" step that can be long running on large well-mapped codebases

The new progress logging system was added to all `scan_for_files` and `scan_for_packages` in https://github.com/nexB/scancode.io/pull/909

> Same for flag_mapped_resources_archives_and_ignored_directories

I'm not sure adding progress logging for "flag" steps is pertinent. I would suggest instead that we improve the function to run as a single `UPDATE` query instead of the current loop. This would make this step fast enough to make any type of progress logging useless.

@AyanSinhaMahapatra I've made some changes to `flag_processed_archives` in https://github.com/nexB/scancode.io/pull/909/commits/a4cbd58e452c391799edafb3d12eae449ea5297c to simplify the code and remove un-necessary queries.
Could you give it a shot to convert this logic into a single SQL query?
